type Product = {
    id: number;
    image: string;
    name: string;
    description: string;
    price: string;
    discountPrice: string | null;
    discount: string | null;
    isNew?: boolean;
  };
  

 const products: Product[] = [
  {
    id: 1,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 2,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 3,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 4,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 5,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 6,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 7,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 8,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 9,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 10,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 11,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 12,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 13,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 14,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 15,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 16,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 17,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 18,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 19,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 20,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 21,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 22,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 23,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 24,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 25,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 26,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 27,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 28,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 29,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 30,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 31,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 32,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 33,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 34,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 35,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 36,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
  {
    id: 37,
    image: "/assets/image 1.png",
    name: "Sytherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: "Rp 3.500.000",
    discount: "-30%",
  },
  {
    id: 38,
    image: "/assets/image 2.png",
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    discountPrice: null,
    discount: null,
  },
  {
    id: 39,
    image: "/assets/image 3.png",
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.000",
    discountPrice: "Rp 14.000.000",
    discount: "-50%",
  },
  {
    id: 40,
    image: "/assets/image 4.png",
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    discountPrice: null,
    discount: null,
    isNew: true,
  },
];
export default products